#### Question 1:
#### Write a program that calculates and prints the value according to the given formula:
#### Q = Square root of [(2 * C * D)/H]
#### Following are the fixed values of C and H:
#### C is 50. H is 30.
#### D is the variable whose values should be input to your program in a comma-separated sequence.
#### Example
#### Let us assume the following comma separated input sequence is given to the program:
#### 100,150,180
#### The output of the program should be:
#### 18,22,24

In [3]:
import math
C = 50
H = 30
def calc(lst):
    out = []
    for D in lst:
        Q =  math.sqrt((2 * C * D)/H)
        out.append(math.floor(Q))
    return out

k = calc([100,150,180])
print(k)

[18, 22, 24]


#### Question 2:
#### Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
#### Note: i=0,1.., X-1; j=0,1,¡Y-1.
#### Example
#### Suppose the following inputs are given to the program:
#### 3,5
#### Then, the output of the program should be:
#### [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [15]:
import numpy as np
def c_arr(x,y):
    arr = np.arange(x*y)
    arr1 = arr.reshape(x,y)
    return arr1

p = c_arr(3,5)
print(p)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### Question 3:
#### Write a program that accepts a comma separated sequence of words as input and prints the
#### words in a comma-separated sequence after sorting them alphabetically.
#### Suppose the following input is supplied to the program:
#### without,hello,bag,world
#### Then, the output should be:
#### bag,hello,without,world

In [3]:
words = input("enter th comma separated words")

w_lst = words.split(',')

s = sorted(w_lst)

n_lst = ','.join(s)
print(n_lst)

enter th comma separated wordslover,lokey,lokesh,chepak
chepak,lokesh,lokey,lover


#### Question 4:
#### Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
#### Suppose the following input is supplied to the program:
#### hello world and practice makes perfect and hello world again
#### Then, the output should be:
#### again and hello makes perfect practice world

In [4]:
words = input("enter the space separted words")
w_lst = words.split()
s = list(set(w_lst))
n_s = sorted(s)
n_lst = " ".join(n_s)
print(n_lst)

enter the space separted wordslover lokey lokesh chepak
chepak lokesh lokey lover


#### Question 5:
#### Write a program that accepts a sentence and calculate the number of letters and digits.
#### Suppose the following input is supplied to the program:
#### hello world! 123
#### Then, the output should be:
#### LETTERS 10
#### DIGITS 3

In [15]:
ip = input("enter the sentence : ")
digit = 0
strng = 0
for i in ip:
    if i.isdigit():
        digit+=1
    elif i.isalpha():
        strng+=1
    else:
        pass
print(f"LETTERS {strng}")
print(f"DIGITS {digit}")

enter the sentence : hello world! 123
LETTERS 10
DIGITS 3


#### Question 6:
#### A website requires the users to input username and password to register. Write a program to
#### check the validity of password input by users.
#### Following are the criteria for checking the password:
#### 1. At least 1 letter between [a-z]
#### 2. At least 1 number between [0-9]
#### 1. At least 1 letter between [A-Z]
#### 3. At least 1 character from [$#@]
#### 4. Minimum length of transaction password: 6
#### 5. Maximum length of transaction password: 12
#### Your program should accept a sequence of comma separated passwords and will check them
#### according to the above criteria. Passwords that match the criteria are to be printed, each
#### separated by a comma.
#### Example
#### If the following passwords are given as input to the program:
#### ABd1234@1,a F1#,2w3E*,2We3345
#### Then, the output of the program should be:
#### ABd1234@1

In [19]:
import re

def check_password_validity(password):
    if len(password) < 6 or len(password) > 12:
        return False
    if not re.search(r'[a-z]', password):
        return False
    if not re.search(r'[0-9]', password):
        return False
    if not re.search(r'[A-Z]', password):
        return False
    if not re.search(r'[$#@]', password):
        return False
    return True

def validate_passwords(passwords):
    valid_passwords = []
    for password in passwords:
        if check_password_validity(password):
            valid_passwords.append(password)
    return valid_passwords


password_input = input("Enter comma-separated passwords: ")
passwords = password_input.split(',')
valid_passwords = validate_passwords(passwords)

print("Valid passwords:", ", ".join(valid_passwords))


Enter comma-separated passwords: ABd1234@1,a F1#,2w3E*,2We3345
Valid passwords: ABd1234@1


False