#### 1. Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np

arr1 = np.arange(1,10)

arr2 = np.arange(5,14)

mat1 = arr1.reshape(3,3)
mat2 = arr2.reshape(3,3)

print(mat1+mat2)

[[ 6  8 10]
 [12 14 16]
 [18 20 22]]


#### 2. Write a Python Program to Multiply Two Matrices?

In [3]:
print(mat1*mat2)

[[  5  12  21]
 [ 32  45  60]
 [ 77  96 117]]


#### 3. Write a Python Program to Transpose a Matrix?

In [4]:
print(mat1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [12]:
sentence = input("Enter a sentence: ")
words = [*sentence]
l=sorted(words)
print(l)



Enter a sentence: lokesh
['e', 'h', 'k', 'l', 'o', 's']


#### 5. Write a Python Program to Remove Punctuation From a String?

In [17]:
import re
s = input("Enter some text")
s = s.lower()
r = re.sub('[^a-zA-Z0-9]'," ",s)
print(r)
    

Enter some textyou @are $the Right
you  are  the right
